"use client";

import { useRef, useState, useCallback, useEffect } from "react";
import type {
  OrbState,
  Message,
  SessionStatus,
  RealtimeServerEvent,
  UploadedFile,
  OutputMode,
  ParsedData,
} from "./types";
import { executeClientTool } from "./tools";

const OPENAI_REALTIME_URL = "https://api.openai.com/v1/realtime/calls";
const MODEL = "gpt-realtime-1.5";
const FETCH_TIMEOUT_MS = 15_000;
const TOOL_FETCH_TIMEOUT_MS = 30_000;

export interface ChartConfig {
  id: string;
  chart_type: "bar" | "line" | "pie" | "area" | "scatter";
  title: string;
  data: Array<Record<string, string | number>>;
  x_label?: string;
  y_label?: string;
  series?: string[];
  /** Data coverage: "847 of 1,000 rows" — shown beneath chart for verification */
  coverage?: string;
  /** Ground truth data summary — displayed in collapsible panel for output verification */
  dataSummary?: string;
}

interface InsightItem {
  type: string;
  severity: string;
  observation: string;
  implication: string;
  recommendation: string;
  spoken: string;
  impact: number;
}

export interface DashboardData {
  title: string;
  subtitle: string;
  kpis: Array<{ label: string; value: string; rawValue: number; column: string; isPercent: boolean; delta?: string; deltaPositive?: boolean }>;
  charts: ChartConfig[];
  insights: InsightItem[];
  risks: InsightItem[];
  opportunities: InsightItem[];
  drilldowns: string[];
}

export interface UseRealtimeSession {
  orbState: OrbState;
  sessionStatus: SessionStatus;
  messages: Message[];
  connect: () => Promise<void>;
  disconnect: () => void;
  sendFileContext: (fileName: string, content: string, parsedData?: import("@/lib/types").ParsedData) => void;
  isConnecting: boolean;
  error: string | null;
  charts: ChartConfig[];
  focusedChartId: string | null;
  removeChart: (id: string) => void;
  clearCharts: () => void;
  focusChart: (id: string) => void;
  drilldowns: string[];
  sendDrilldown: (text: string) => void;
  /** Dashboard generated by generate_dashboard tool */
  activeDashboard: DashboardData | null;
  closeDashboard: () => void;
}

interface PendingFunctionCall {
  callId: string;
  name: string;
  args: string;
}

// ── Helpers ──────────────────────────────────────────────

function classifyMicError(err: unknown): string {
  if (err instanceof DOMException) {
    switch (err.name) {
      case "NotAllowedError":
        return "Microphone access denied. Please allow microphone access and try again.";
      case "NotFoundError":
        return "No microphone found. Please connect a microphone and try again.";
      case "NotReadableError":
        return "Microphone is in use by another application.";
      case "OverconstrainedError":
        return "Microphone does not support the required audio settings.";
      default:
        return `Microphone error: ${err.message}`;
    }
  }
  return "Could not access microphone.";
}

function log(tag: string, ...args: unknown[]) {
  console.log(`[realtime:${tag}]`, ...args);
}

function logError(tag: string, ...args: unknown[]) {
  console.error(`[realtime:${tag}]`, ...args);
}

/** Safely parse JSON tool args. Returns empty object on failure. */
function safeParseArgs(raw: string, toolName: string): Record<string, unknown> {
  if (!raw || raw.trim() === "") {
    log("tool", `${toolName}: no args provided, using empty object`);
    return {};
  }
  try {
    const parsed = JSON.parse(raw);
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
      logError("tool", `${toolName}: args parsed but not an object:`, parsed);
      return {};
    }
    return parsed as Record<string, unknown>;
  } catch {
    logError("tool", `${toolName}: failed to parse args JSON:`, raw);
    return {};
  }
}

/** Resolve file_name from tool args. Falls back to the most recently uploaded file. */
function resolveFile(
  args: Record<string, unknown>,
  files: UploadedFile[]
): UploadedFile | null {
  const readyFiles = files.filter((f) => f.status === "ready");
  if (readyFiles.length === 0) return null;

  const explicit = args.file_name as string | undefined;
  if (explicit) {
    const match = readyFiles.find(
      (f) => f.name.toLowerCase() === explicit.toLowerCase()
    );
    if (match) return match;
    // Partial match fallback
    const partial = readyFiles.find(
      (f) => f.name.toLowerCase().includes(explicit.toLowerCase())
    );
    if (partial) {
      log("tool", `Resolved "${explicit}" → "${partial.name}" (partial match)`);
      return partial;
    }
    return null;
  }

  // No file_name specified — only default if there's exactly one file (unambiguous)
  if (readyFiles.length === 1) {
    log("tool", `No file_name in args — using only uploaded file "${readyFiles[0].name}"`);
    return readyFiles[0];
  }

  // Multiple files and no explicit name — refuse to guess
  log("tool", `No file_name in args and ${readyFiles.length} files uploaded — cannot determine which file to use`);
  return null;
}

export interface RealtimeSessionOptions {
  initialMessages?: Message[];
  initialCharts?: ChartConfig[];
  initialDashboard?: DashboardData | null;
  onSave?: (data: {
    messages: Message[];
    charts: ChartConfig[];
    dashboard: DashboardData | null;
    outputMode: OutputMode;
  }) => void;
}

export function useRealtimeSession(
  files: UploadedFile[],
  mode: OutputMode = "executive",
  language: string = "en",
  options: RealtimeSessionOptions = {}
): UseRealtimeSession {
  const [orbState, setOrbState] = useState<OrbState>("idle");
  const [sessionStatus, setSessionStatus] =
    useState<SessionStatus>("disconnected");
  const [messages, setMessages] = useState<Message[]>(options.initialMessages ?? []);
  const [isConnecting, setIsConnecting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [charts, setCharts] = useState<ChartConfig[]>(options.initialCharts ?? []);
  const [focusedChartId, setFocusedChartId] = useState<string | null>(null);
  const [drilldowns, setDrilldowns] = useState<string[]>([]);
  const [activeDashboard, setActiveDashboard] = useState<DashboardData | null>(options.initialDashboard ?? null);
  const onSaveRef = useRef(options.onSave);

  const pcRef = useRef<RTCPeerConnection | null>(null);
  const dcRef = useRef<RTCDataChannel | null>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const audioElRef = useRef<HTMLAudioElement | null>(null);
  const connectingRef = useRef(false);
  const greetingPendingRef = useRef(false);

  const currentAssistantIdRef = useRef<string | null>(null);
  const currentUserItemIdRef = useRef<string | null>(null);
  const pendingCallRef = useRef<PendingFunctionCall | null>(null);
  const filesRef = useRef(files);
  filesRef.current = files;

  // ── Response lifecycle tracking ────────────────────────
  // Prevents "conversation_already_has_active_response" errors
  const responseActiveRef = useRef(false);
  const pendingResponseCreateRef = useRef(false);

  // ── Send event on data channel ─────────────────────────
  const sendDC = useCallback((payload: Record<string, unknown>) => {
    const dc = dcRef.current;
    if (dc && dc.readyState === "open") {
      dc.send(JSON.stringify(payload));
      return true;
    }
    return false;
  }, []);

  /** Safe response.create — only sends if no response is currently active.
   *  If one is active, defers until response.done fires. */
  const requestResponse = useCallback(() => {
    if (responseActiveRef.current) {
      log("response", "Deferring response.create — response already active");
      pendingResponseCreateRef.current = true;
      return;
    }
    if (sendDC({ type: "response.create" })) {
      log("response", "Sent response.create");
    }
  }, [sendDC]);

  // ── Execute a tool call and send result back ───────────
  const executeTool = useCallback(
    async (call: PendingFunctionCall) => {
      log("tool", `┌ Executing: ${call.name} (call_id: ${call.callId})`);
      log("tool", `│ Raw args: ${call.args || "(empty)"}`);

      const args = safeParseArgs(call.args, call.name);
      log("tool", `│ Parsed args:`, args);

      // Try client-side first
      const clientResult = executeClientTool(call.name, args, filesRef.current);

      let resultText = "Tool execution produced no result.";
      let chartData: ChartConfig | null = null;

      if (clientResult) {
        resultText = clientResult.result;
        log("tool", `│ Resolved client-side`);
      } else {
        // Resolve file — with fallback to active/latest file
        const file = resolveFile(args, filesRef.current);
        const fileName = file?.name;

        log("tool", `│ File context: ${fileName ?? "none"} (${filesRef.current.length} files available)`);

        if (!file && call.name !== "list_uploaded_files") {
          const available = filesRef.current
            .filter((f) => f.status === "ready")
            .map((f) => f.name);
          if (available.length === 0) {
            resultText = "No files have been uploaded yet. Ask the user to upload a CSV, Excel, or PDF file.";
          } else if (args.file_name) {
            resultText = `Could not resolve file "${args.file_name}". Available files: ${available.join(", ")}. Specify the exact file name.`;
          } else {
            resultText = `Multiple files are uploaded: ${available.join(", ")}. Specify which file to use by setting file_name.`;
          }
          log("tool", `│ No file resolved`);
        } else if (call.name !== "list_uploaded_files") {
          try {
            // Override file_name in args with the resolved name
            const resolvedArgs = fileName
              ? { ...args, file_name: fileName }
              : args;

            // For compare_files, resolve second file
            let parsedDataB: unknown = undefined;
            if (call.name === "compare_files" && args.file_name_b) {
              const fileB = filesRef.current.find(
                (f) => f.name.toLowerCase() === String(args.file_name_b).toLowerCase() && f.status === "ready"
              ) ?? filesRef.current.find(
                (f) => f.name.toLowerCase().includes(String(args.file_name_b).toLowerCase()) && f.status === "ready"
              );
              if (fileB) {
                parsedDataB = fileB.parsedData;
                log("tool", `│ Second file for comparison: ${fileB.name}`);
              }
            }

            const res = await fetch("/api/tools/execute", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                tool: call.name,
                args: resolvedArgs,
                fileContent: file?.content,
                fileName,
                parsedData: file?.parsedData,
                ...(parsedDataB ? { parsedDataB } : {}),
              }),
              signal: AbortSignal.timeout(TOOL_FETCH_TIMEOUT_MS),
            });

            if (!res.ok) {
              const errBody = (await res.json().catch(() => ({ error: "Unknown server error" }))) as { error: string };
              resultText = `Error: ${errBody.error}`;
              logError("tool", `│ Server error:`, errBody.error);
            } else {
              const data = (await res.json()) as {
                result: string;
                chart?: ChartConfig;
                drilldowns?: string[];
                dashboard?: DashboardData;
              };
              resultText = data.result;
              if (data.chart) chartData = data.chart;
              if (data.dashboard) {
                setActiveDashboard(data.dashboard);
                log("tool", `│ Dashboard generated: ${data.dashboard.title}`);
              }
              if (data.drilldowns && data.drilldowns.length > 0) {
                setDrilldowns(data.drilldowns);
              }
              log("tool", `│ Server OK`);
            }
          } catch (err) {
            if (err instanceof DOMException && err.name === "TimeoutError") {
              resultText = `Tool timed out after ${TOOL_FETCH_TIMEOUT_MS / 1000}s. The data may be too large.`;
            } else {
              resultText = `Tool execution failed: ${err instanceof Error ? err.message : "unknown error"}`;
            }
            logError("tool", `│ Exception:`, resultText);
          }
        }
      }

      // Show chart if generated
      if (chartData) {
        const chartWithId = { ...chartData, id: `chart-${Date.now()}` };
        setCharts((prev) => [...prev, chartWithId]);
        setFocusedChartId(chartWithId.id);
        log("tool", `│ Chart created: ${chartData.title}`);
      }

      log("tool", `└ Done: ${call.name}`);

      // Send result back to the assistant
      sendDC({
        type: "conversation.item.create",
        item: {
          type: "function_call_output",
          call_id: call.callId,
          output: resultText,
        },
      });

      // Trigger the assistant to continue — using the safe guard
      requestResponse();
    },
    [sendDC, requestResponse]
  );

  // ── Cleanup ────────────────────────────────────────────
  const cleanup = useCallback(() => {
    log("lifecycle", "Cleaning up session resources");

    if (dcRef.current) {
      dcRef.current.onopen = null;
      dcRef.current.onmessage = null;
      dcRef.current.onclose = null;
      dcRef.current.close();
      dcRef.current = null;
    }

    if (pcRef.current) {
      pcRef.current.ontrack = null;
      pcRef.current.oniceconnectionstatechange = null;
      pcRef.current.close();
      pcRef.current = null;
    }

    streamRef.current?.getTracks().forEach((t) => t.stop());
    streamRef.current = null;

    if (audioElRef.current) {
      audioElRef.current.pause();
      audioElRef.current.srcObject = null;
      audioElRef.current = null;
    }

    currentAssistantIdRef.current = null;
    currentUserItemIdRef.current = null;
    pendingCallRef.current = null;
    connectingRef.current = false;
    greetingPendingRef.current = false;
    responseActiveRef.current = false;
    pendingResponseCreateRef.current = false;
  }, []);

  // Keep onSave ref current
  onSaveRef.current = options.onSave;

  const disconnect = useCallback(() => {
    // Persist state before tearing down
    if (onSaveRef.current) {
      // Read latest state via setState callbacks to avoid stale closures
      setMessages((msgs) => {
        setCharts((chts) => {
          setActiveDashboard((dash) => {
            if (msgs.length > 0 || chts.length > 0 || dash) {
              onSaveRef.current?.({ messages: msgs, charts: chts, dashboard: dash, outputMode: mode });
            }
            return dash;
          });
          return chts;
        });
        return msgs;
      });
    }

    cleanup();
    setSessionStatus("disconnected");
    setOrbState("idle");
    setIsConnecting(false);
    setError(null);
    log("lifecycle", "Disconnected (state saved)");
  }, [cleanup, mode]);

  // ── Handle data-channel events ─────────────────────────
  const handleServerEvent = useCallback(
    (evt: RealtimeServerEvent) => {
      switch (evt.type) {
        case "session.created":
          setSessionStatus("connected");
          setOrbState("idle");
          log("session", "session.created");
          if (dcRef.current?.readyState === "open") {
            requestResponse();
          } else {
            greetingPendingRef.current = true;
          }
          break;

        case "session.updated":
          setSessionStatus("connected");
          setOrbState("idle");
          break;

        case "input_audio_buffer.speech_started":
          setOrbState("listening");
          {
            const id = `user-${Date.now()}`;
            currentUserItemIdRef.current = id;
            setMessages((prev) => [
              ...prev,
              { id, role: "user", content: "", timestamp: Date.now(), streaming: true },
            ]);
          }
          break;

        case "input_audio_buffer.speech_stopped":
          setOrbState("thinking");
          if (currentUserItemIdRef.current) {
            const uid = currentUserItemIdRef.current;
            setMessages((prev) =>
              prev.map((m) => (m.id === uid ? { ...m, streaming: false } : m))
            );
          }
          break;

        case "conversation.item.input_audio_transcription.delta": {
          const delta = evt.delta as string | undefined;
          const itemId = currentUserItemIdRef.current;
          if (itemId && delta) {
            setMessages((prev) =>
              prev.map((m) =>
                m.id === itemId ? { ...m, content: m.content + delta } : m
              )
            );
          }
          break;
        }

        case "conversation.item.input_audio_transcription.completed": {
          const transcript = evt.transcript as string | undefined;
          const itemId = currentUserItemIdRef.current;
          if (itemId && transcript) {
            setMessages((prev) =>
              prev.map((m) =>
                m.id === itemId ? { ...m, content: transcript, streaming: false } : m
              )
            );
          }
          currentUserItemIdRef.current = null;
          break;
        }

        // ── Response lifecycle ───────────────────────────
        case "response.created": {
          responseActiveRef.current = true;
          setOrbState("thinking");
          const response = evt.response as { id: string } | undefined;
          currentAssistantIdRef.current = response?.id ?? `resp-${Date.now()}`;
          log("response", `Active: ${currentAssistantIdRef.current}`);
          break;
        }

        case "response.done": {
          responseActiveRef.current = false;
          currentAssistantIdRef.current = null;
          log("response", "Done");

          // Flush any deferred response.create
          if (pendingResponseCreateRef.current) {
            pendingResponseCreateRef.current = false;
            log("response", "Flushing deferred response.create");
            // Small delay to let the server process the done event
            setTimeout(() => requestResponse(), 50);
          }
          break;
        }

        case "response.output_item.added": {
          const item = evt.item as { type?: string; call_id?: string; name?: string; id?: string } | undefined;
          if (item?.type === "function_call") {
            pendingCallRef.current = {
              callId: item.call_id ?? item.id ?? `call-${Date.now()}`,
              name: item.name ?? "unknown",
              args: "",
            };
            log("tool", `Function call started: ${item.name}`);
          } else if (item?.type === "message") {
            const rid = currentAssistantIdRef.current;
            if (rid) {
              setMessages((prev) => {
                if (prev.some((m) => m.id === rid)) return prev;
                return [...prev, { id: rid, role: "assistant", content: "", timestamp: Date.now(), streaming: true }];
              });
            }
          }
          break;
        }

        case "response.function_call_arguments.delta": {
          const delta = evt.delta as string | undefined;
          if (pendingCallRef.current && delta) {
            pendingCallRef.current.args += delta;
          }
          break;
        }

        case "response.function_call_arguments.done": {
          const finalArgs = evt.arguments as string | undefined;
          if (pendingCallRef.current) {
            if (finalArgs) pendingCallRef.current.args = finalArgs;
            const call = { ...pendingCallRef.current };
            pendingCallRef.current = null;
            executeTool(call);
          }
          break;
        }

        case "response.audio_transcript.delta": {
          setOrbState("speaking");
          const delta = evt.delta as string | undefined;
          const rid = currentAssistantIdRef.current;
          if (rid && delta) {
            setMessages((prev) => {
              const exists = prev.some((m) => m.id === rid);
              if (!exists) {
                return [...prev, { id: rid, role: "assistant", content: delta, timestamp: Date.now(), streaming: true }];
              }
              return prev.map((m) => (m.id === rid ? { ...m, content: m.content + delta } : m));
            });
          }
          break;
        }

        case "response.audio_transcript.done": {
          const transcript = evt.transcript as string | undefined;
          const rid = currentAssistantIdRef.current;
          if (rid && transcript) {
            setMessages((prev) =>
              prev.map((m) => (m.id === rid ? { ...m, content: transcript, streaming: false } : m))
            );
          }
          break;
        }

        case "response.audio.done":
          setTimeout(() => setOrbState("idle"), 400);
          break;

        case "error": {
          const errObj = evt.error as { message?: string; code?: string } | undefined;
          const errMsg = errObj?.message ?? "Unknown error";
          const errCode = errObj?.code ?? "?";
          logError("event", `Server error (${errCode}): ${errMsg}`);
          // If error is about active response, clear the flag so deferred creates can proceed
          if (errCode === "conversation_already_has_active_response") {
            log("response", "Clearing active flag due to conflict error");
            // Don't show this to the user — it's an internal timing issue
            responseActiveRef.current = false;
          } else {
            setError(errMsg);
          }
          setOrbState("idle");
          break;
        }

        default:
          break;
      }
    },
    [executeTool, requestResponse]
  );

  // ── Connect ────────────────────────────────────────────
  const connect = useCallback(async () => {
    if (connectingRef.current) {
      log("lifecycle", "Connect already in progress, ignoring");
      return;
    }

    if (pcRef.current) {
      disconnect();
    }

    connectingRef.current = true;
    setIsConnecting(true);
    setError(null);
    setSessionStatus("connecting");
    setMessages([]);
    setCharts([]);
    setFocusedChartId(null);

    try {
      log("lifecycle", "Requesting ephemeral token");
      const tokenRes = await fetch(`/api/realtime/session?mode=${mode}&lang=${language}`, {
        method: "POST",
        signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      });
      if (!tokenRes.ok) {
        const body = await tokenRes.json().catch(() => ({})) as { error?: string };
        throw new Error(body.error ?? `Session creation failed (${tokenRes.status})`);
      }
      const { clientSecret } = (await tokenRes.json()) as {
        clientSecret: string;
        expiresAt: number;
      };
      log("lifecycle", "Token received");

      log("lifecycle", "Requesting microphone access");
      let stream: MediaStream;
      try {
        stream = await navigator.mediaDevices.getUserMedia({
          audio: { echoCancellation: true, noiseSuppression: true, sampleRate: 24000 },
        });
      } catch (micErr) {
        throw new Error(classifyMicError(micErr));
      }
      streamRef.current = stream;
      log("lifecycle", "Microphone access granted");

      const pc = new RTCPeerConnection();
      pcRef.current = pc;

      pc.ontrack = (e) => {
        if (!audioElRef.current) {
          audioElRef.current = new Audio();
          audioElRef.current.autoplay = true;
        }
        audioElRef.current.srcObject = e.streams[0];
      };

      stream.getTracks().forEach((track) => pc.addTrack(track, stream));

      const dc = pc.createDataChannel("oai-events");
      dcRef.current = dc;

      dc.onopen = () => {
        setSessionStatus("connected");
        setIsConnecting(false);
        connectingRef.current = false;
        log("lifecycle", "Data channel open — session live");
        if (greetingPendingRef.current) {
          greetingPendingRef.current = false;
          requestResponse();
        }
      };

      dc.onmessage = (e) => {
        try {
          const event = JSON.parse(e.data) as RealtimeServerEvent;
          handleServerEvent(event);
        } catch (parseErr) {
          logError("dc", "Failed to parse data channel message:", parseErr);
        }
      };

      dc.onclose = () => {
        log("lifecycle", "Data channel closed");
        setSessionStatus("disconnected");
        setOrbState("idle");
      };

      pc.oniceconnectionstatechange = () => {
        const state = pc.iceConnectionState;
        log("ice", state);
        if (state === "failed" || state === "disconnected") {
          setSessionStatus("disconnected");
          setOrbState("idle");
          setError("Connection lost — tap the orb to reconnect");
          setIsConnecting(false);
          connectingRef.current = false;
        }
      };

      log("lifecycle", "Starting SDP negotiation");
      const offer = await pc.createOffer();
      await pc.setLocalDescription(offer);

      const sdpRes = await fetch(
        `${OPENAI_REALTIME_URL}?model=${MODEL}`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${clientSecret}`,
            "Content-Type": "application/sdp",
          },
          body: offer.sdp,
          signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
        }
      );

      if (!sdpRes.ok) {
        const errorBody = await sdpRes.text();
        logError("sdp", `Negotiation failed (${sdpRes.status}):`, errorBody);
        throw new Error(`WebRTC negotiation failed (${sdpRes.status})`);
      }

      const answerSdp = await sdpRes.text();
      await pc.setRemoteDescription({ type: "answer", sdp: answerSdp });
      log("lifecycle", "SDP negotiation complete — WebRTC connected");
    } catch (err) {
      let msg: string;
      if (err instanceof DOMException && err.name === "TimeoutError") {
        msg = "Connection timed out. Please check your network and try again.";
      } else {
        msg = err instanceof Error ? err.message : "Connection failed";
      }
      logError("connect", msg);
      setError(msg);
      setSessionStatus("error");
      setOrbState("idle");
      setIsConnecting(false);
      connectingRef.current = false;
      cleanup();
    }
  }, [disconnect, cleanup, handleServerEvent, requestResponse]);

  // ── Send file context ──────────────────────────────────
  const sendFileContext = useCallback(
    (fileName: string, _content: string, parsedData?: ParsedData) => {
      // SAFETY: Send ONLY metadata to the AI — never raw file content.
      // The AI must use tools (profile_dataset, run_analysis, create_chart) to access data.
      // This prevents the AI from reading raw data and bypassing validation/confidence scoring.
      const safeName = fileName.replace(/[^a-zA-Z0-9_.\-\s]/g, "");
      let metadata: string;

      if (parsedData) {
        const pd = parsedData;
        const colList = pd.columns.map((c: string) => `${c} (${pd.columnTypes[c] ?? "unknown"})`).join(", ");
        metadata = `File uploaded: "${safeName}"\nRows: ${parsedData.totalRows}\nColumns: ${colList}\n\nUse profile_dataset to explore this file. Do NOT guess column names — use the exact names listed above.`;
      } else {
        metadata = `File uploaded: "${safeName}"\n\nUse profile_dataset to explore this file before analyzing it.`;
      }

      if (!sendDC({
        type: "conversation.item.create",
        item: {
          type: "message",
          role: "user",
          content: [{ type: "input_text", text: metadata }],
        },
      })) {
        log("file", "Data channel not open — file context not sent");
        return;
      }

      setMessages((prev) => [
        ...prev,
        { id: `file-${Date.now()}`, role: "user", content: `Uploaded ${fileName}`, timestamp: Date.now() },
      ]);

      requestResponse();
      log("file", `Injected metadata for ${fileName} (no raw content sent)`);
    },
    [sendDC, requestResponse]
  );

  const removeChart = useCallback((id: string) => {
    setCharts((prev) => prev.filter((c) => c.id !== id));
    setFocusedChartId((prev) => (prev === id ? null : prev));
  }, []);

  const clearCharts = useCallback(() => {
    setCharts([]);
    setFocusedChartId(null);
  }, []);

  const focusChart = useCallback((id: string) => {
    setFocusedChartId(id);
  }, []);

  /** Send a drill-down as a contextual follow-up — framed as continuation, not a new question */
  const sendDrilldown = useCallback(
    (text: string) => {
      // Frame as a continuation so the assistant doesn't restart from scratch
      const contextualPrompt = `Following up on what you just showed me: ${text}. Continue from where you left off — this is a drill-down, not a new question.`;

      if (!sendDC({
        type: "conversation.item.create",
        item: {
          type: "message",
          role: "user",
          content: [{ type: "input_text", text: contextualPrompt }],
        },
      })) {
        return;
      }

      // Show the short label in the transcript, not the full framing
      setMessages((prev) => [
        ...prev,
        { id: `drill-${Date.now()}`, role: "user", content: text, timestamp: Date.now() },
      ]);

      setDrilldowns([]);
      requestResponse();
      log("drilldown", `Sent: ${text}`);
    },
    [sendDC, requestResponse]
  );

  const closeDashboard = useCallback(() => setActiveDashboard(null), []);

  useEffect(() => {
    return () => cleanup();
  }, [cleanup]);

  return {
    orbState,
    sessionStatus,
    messages,
    connect,
    disconnect,
    sendFileContext,
    isConnecting,
    error,
    charts,
    focusedChartId,
    removeChart,
    clearCharts,
    focusChart,
    drilldowns,
    sendDrilldown,
    activeDashboard,
    closeDashboard,
  };
}
