"use client";

import { useRef, useState, useCallback, useEffect } from "react";
import type {
  OrbState,
  Message,
  SessionStatus,
  RealtimeServerEvent,
  UploadedFile,
  OutputMode,
  ParsedData,
} from "./types";
import { executeClientTool } from "./tools";
import { composeScene, composeSceneFromPassages } from "./visual/composer";
import { progressSkeletonFragment } from "./visual/fragments";
import type { VisualScene, SceneIntent, ChartProps } from "./visual/scene-types";
import type { DocumentType, Fact, Metric, TimelineEvent, Entity, SourceSpan } from "./documents/types";

const OPENAI_REALTIME_URL = "https://api.openai.com/v1/realtime/calls";
const MODEL = "gpt-realtime-1.5";
const FETCH_TIMEOUT_MS = 15_000;
const TOOL_FETCH_TIMEOUT_MS = 30_000;
/** Longer client-side fetch budget for tools that may trigger LLM extraction.
 *  Must exceed the server-side timeout in tools/execute/route.ts (120s) to
 *  avoid the client aborting before the server responds on first-query
 *  extraction passes against long narrative PDFs. */
const LLM_TOOL_FETCH_TIMEOUT_MS = 135_000;
const LONG_RUNNING_TOOLS = new Set([
  "query_document",
  "query_document_v2",
  "compose_visual_scene",
]);
const PROGRESS_POLL_INTERVAL_MS = 500;

export interface ChartConfig {
  id: string;
  chart_type: "bar" | "line" | "pie" | "area" | "scatter";
  title: string;
  data: Array<Record<string, string | number>>;
  x_label?: string;
  y_label?: string;
  series?: string[];
  /** Data coverage: "847 of 1,000 rows" — shown beneath chart for verification */
  coverage?: string;
  /** Ground truth data summary — displayed in collapsible panel for output verification */
  dataSummary?: string;
}

interface InsightItem {
  type: string;
  severity: string;
  observation: string;
  implication: string;
  recommendation: string;
  spoken: string;
  impact: number;
}

export interface DashboardData {
  title: string;
  subtitle: string;
  kpis: Array<{ label: string; value: string; rawValue: number; column: string; isPercent: boolean; delta?: string; deltaPositive?: boolean }>;
  charts: ChartConfig[];
  insights: InsightItem[];
  risks: InsightItem[];
  opportunities: InsightItem[];
  drilldowns: string[];
}

/**
 * Phase 2: structured response from query_document. Stored on hook state
 * so Phase 3's visual composer can render risk panels, entity cards,
 * timelines, etc. In Phase 2 only the spoken answer is consumed.
 */
export interface DocumentQueryResponse {
  fileName: string;
  answer: string;
  /** v1 (legacy query_document) only. Phase 1 v2 returns `passages` instead. */
  facts?: unknown[];
  /** v1 only. */
  metrics?: unknown[];
  /** v1 only. */
  timeline?: unknown[];
  /** v2 (query_document_v2) only — retrieved + reranked passages. */
  passages?: unknown[];
  citations: Array<{ spanId?: string; page?: number | null; text: string; chunkIndex?: number; pageEnd?: number | null; passageId?: string }>;
  confidence: "high" | "medium" | "low";
  suggestedVisuals: string[];
  timestamp: number;
}

export interface UseRealtimeSession {
  orbState: OrbState;
  sessionStatus: SessionStatus;
  messages: Message[];
  connect: () => Promise<void>;
  disconnect: () => void;
  sendFileContext: (
    fileName: string,
    content: string,
    parsedData?: import("@/lib/types").ParsedData,
    extraction?: import("@/lib/documents/types").DocumentExtraction,
    hasPassages?: boolean
  ) => void;
  isConnecting: boolean;
  error: string | null;
  charts: ChartConfig[];
  focusedChartId: string | null;
  removeChart: (id: string) => void;
  clearCharts: () => void;
  focusChart: (id: string) => void;
  drilldowns: string[];
  sendDrilldown: (text: string) => void;
  /** Dashboard generated by generate_dashboard tool */
  activeDashboard: DashboardData | null;
  closeDashboard: () => void;
  /** Phase 2: latest query_document result. Phase 3 visual layer will consume this. */
  documentQuery: DocumentQueryResponse | null;
  /** Phase 3: composed visual scenes — the new primary visual state. */
  scenes: VisualScene[];
  removeScene: (id: string) => void;
  clearScenes: () => void;
}

interface PendingFunctionCall {
  callId: string;
  name: string;
  args: string;
}

// ── Helpers ──────────────────────────────────────────────

function classifyMicError(err: unknown): string {
  if (err instanceof DOMException) {
    switch (err.name) {
      case "NotAllowedError":
        return "Microphone access denied. Please allow microphone access and try again.";
      case "NotFoundError":
        return "No microphone found. Please connect a microphone and try again.";
      case "NotReadableError":
        return "Microphone is in use by another application.";
      case "OverconstrainedError":
        return "Microphone does not support the required audio settings.";
      default:
        return `Microphone error: ${err.message}`;
    }
  }
  return "Could not access microphone.";
}

function log(tag: string, ...args: unknown[]) {
  console.log(`[realtime:${tag}]`, ...args);
}

function logError(tag: string, ...args: unknown[]) {
  console.error(`[realtime:${tag}]`, ...args);
}

// ── Phase 3: tool-result → VisualScene bridge ────────────

const NARRATIVE_TYPE_SET = new Set<DocumentType>([
  "contract",
  "policy",
  "report",
  "memo",
  "financial_statement",
  "invoice",
  "receipt",
  "form",
]);

function focusToIntent(focus?: string): SceneIntent {
  switch (focus) {
    case "risks":       return "risk";
    case "dates":       return "timeline";
    case "metrics":     return "metric";
    case "parties":     return "parties";
    case "obligations": return "obligations";
    case "general":
    default:            return "overview";
  }
}

function chartConfigToChartProps(c: ChartConfig): ChartProps {
  return {
    chart_type: c.chart_type,
    title: c.title,
    data: c.data,
    x_label: c.x_label,
    y_label: c.y_label,
    series: c.series,
    coverage: c.coverage,
    dataSummary: c.dataSummary,
  };
}

interface V1DocumentResponse {
  answer: string;
  facts: Fact[];
  metrics: Metric[];
  timeline: TimelineEvent[];
  entities?: Entity[];
  spans?: Record<string, SourceSpan>;
  citations: Array<{ spanId: string; page?: number; text: string }>;
  confidence: "high" | "medium" | "low";
  suggestedVisuals: string[];
  documentType?: string;
  focus?: string;
}

interface V2DocumentResponse {
  answer: string;
  passages: Array<{
    passageId: string;
    chunkIndex: number;
    pageStart: number | null;
    pageEnd: number | null;
    text: string;
    heading: string | null;
    similarity: number;
  }>;
  citations: Array<{
    passageId: string;
    chunkIndex: number;
    page: number | null;
    pageEnd?: number | null;
    text: string;
  }>;
  confidence: "high" | "medium" | "low";
  suggestedVisuals: string[];
  documentType: string;
  focus?: string;
  rerankerRan?: boolean;
  caveat?: string;
  /** Optional structured numeric data the composer extracted for the
   *  scene composer to render as KPI cards + (optionally) a chart. */
  chartable?: {
    kind: "bar" | "pie" | "line" | "area" | "kpi_only";
    title: string;
    unit: string;
    series: Array<{ label: string; value: number; sourcePage: number | null }>;
  };
  /** Phase 6 — "simple" (single-pass RAG) or "complex" (decomposed). */
  reasoningMode?: "simple" | "complex";
  /** Phase 6 — sub-questions used in a complex answer. */
  subQuestions?: string[];
  /** Phase 6 — sub-answers that succeeded vs. attempted. */
  subAnswersCompleted?: number;
}

interface BridgeToolResult {
  result: string;
  chart?: ChartConfig;
  dashboard?: DashboardData;
  drilldowns?: string[];
  documentResponse?: V1DocumentResponse | V2DocumentResponse;
  scene?: VisualScene;
}

function isV2Response(dr: V1DocumentResponse | V2DocumentResponse): dr is V2DocumentResponse {
  return "passages" in dr && Array.isArray((dr as V2DocumentResponse).passages);
}

/**
 * Convert any tool result into a VisualScene. Returns null when the tool
 * produced no visual material (e.g. profile_dataset returns text only).
 * The bridge is deliberately defensive — partial/unknown data still
 * produces a usable scene rather than throwing.
 */
function bridgeToolResultToScene(
  toolName: string,
  data: BridgeToolResult,
  file: UploadedFile | null,
  args: Record<string, unknown>
): VisualScene | null {
  const fileName = (args.file_name as string | undefined) ?? file?.name ?? "data";
  const documentId = file?.documentId;
  const docType: DocumentType | "spreadsheet" =
    (file?.extraction?.type as DocumentType | undefined) ??
    ((file?.parsedData?.totalRows ?? 0) > 0 ? "spreadsheet" : "report");

  // 1. Direct scene from compose_visual_scene tool — pass through.
  if (data.scene) return data.scene;

  // 2. Dashboard tool → overview scene.
  if (data.dashboard) {
    return composeScene({
      intent: "overview",
      documentType: "spreadsheet",
      documentId,
      fileName,
      kpis: data.dashboard.kpis.map((k) => ({
        column: k.column,
        label: k.label,
        value: k.value,
        rawValue: k.rawValue,
        isPercent: k.isPercent,
        delta: k.delta,
        deltaPositive: k.deltaPositive,
      })),
      charts: data.dashboard.charts.map(chartConfigToChartProps),
      caption: data.dashboard.subtitle,
      drilldowns: data.dashboard.drilldowns,
    });
  }

  // 3. Chart tool → spotlight chart scene.
  if (data.chart) {
    return composeScene({
      intent: "trend",
      documentType: "spreadsheet",
      documentId,
      fileName,
      charts: [chartConfigToChartProps(data.chart)],
      drilldowns: data.drilldowns,
    });
  }

  // 4. Narrative tool result → scene. Two flavors:
  //    - v2 (query_document_v2): passages-based RAG response.
  //    - v1 (legacy query_document, compose_visual_scene): fact-graph response.
  if (data.documentResponse) {
    const dr = data.documentResponse;

    if (isV2Response(dr)) {
      return composeSceneFromPassages({
        documentId,
        fileName,
        documentType: dr.documentType ?? "report",
        question:
          toolName === "query_document_v2" || toolName === "query_document"
            ? (args.question as string | undefined)
            : undefined,
        answer: dr.answer,
        confidence: dr.confidence,
        passages: dr.passages,
        citedPassageIds: dr.citations.map((c) => c.passageId),
        caveat: dr.caveat,
        drilldowns: data.drilldowns,
        chartable: dr.chartable,
      });
    }

    // v1 path (legacy fact graph)
    const narrativeType = (dr.documentType as DocumentType) ?? docType;
    const intent: SceneIntent = NARRATIVE_TYPE_SET.has(narrativeType as DocumentType)
      ? focusToIntent(dr.focus)
      : "overview";
    return composeScene({
      intent,
      documentType: narrativeType,
      documentId,
      fileName,
      question: toolName === "query_document" ? (args.question as string | undefined) : undefined,
      answer: dr.answer,
      facts: dr.facts,
      metrics: dr.metrics,
      timeline: dr.timeline,
      entities: dr.entities,
      spans: dr.spans ?? {},
      confidence: dr.confidence,
    });
  }

  // No visual material in this tool result.
  return null;
}

/** Safely parse JSON tool args. Returns empty object on failure. */
function safeParseArgs(raw: string, toolName: string): Record<string, unknown> {
  if (!raw || raw.trim() === "") {
    log("tool", `${toolName}: no args provided, using empty object`);
    return {};
  }
  try {
    const parsed = JSON.parse(raw);
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
      logError("tool", `${toolName}: args parsed but not an object:`, parsed);
      return {};
    }
    return parsed as Record<string, unknown>;
  } catch {
    logError("tool", `${toolName}: failed to parse args JSON:`, raw);
    return {};
  }
}

/** Resolve file_name from tool args. Falls back to the most recently uploaded file. */
function resolveFile(
  args: Record<string, unknown>,
  files: UploadedFile[]
): UploadedFile | null {
  const readyFiles = files.filter((f) => f.status === "ready");
  if (readyFiles.length === 0) return null;

  const explicit = args.file_name as string | undefined;
  if (explicit) {
    const match = readyFiles.find(
      (f) => f.name.toLowerCase() === explicit.toLowerCase()
    );
    if (match) return match;
    // Partial match fallback
    const partial = readyFiles.find(
      (f) => f.name.toLowerCase().includes(explicit.toLowerCase())
    );
    if (partial) {
      log("tool", `Resolved "${explicit}" → "${partial.name}" (partial match)`);
      return partial;
    }
    return null;
  }

  // No file_name specified — only default if there's exactly one file (unambiguous)
  if (readyFiles.length === 1) {
    log("tool", `No file_name in args — using only uploaded file "${readyFiles[0].name}"`);
    return readyFiles[0];
  }

  // Multiple files and no explicit name — refuse to guess
  log("tool", `No file_name in args and ${readyFiles.length} files uploaded — cannot determine which file to use`);
  return null;
}

export interface RealtimeSessionOptions {
  initialMessages?: Message[];
  initialCharts?: ChartConfig[];
  initialDashboard?: DashboardData | null;
  onSave?: (data: {
    messages: Message[];
    charts: ChartConfig[];
    dashboard: DashboardData | null;
    outputMode: OutputMode;
  }) => void;
}

export function useRealtimeSession(
  files: UploadedFile[],
  mode: OutputMode = "executive",
  language: string = "en",
  options: RealtimeSessionOptions = {}
): UseRealtimeSession {
  const [orbState, setOrbState] = useState<OrbState>("idle");
  const [sessionStatus, setSessionStatus] =
    useState<SessionStatus>("disconnected");
  const [messages, setMessages] = useState<Message[]>(options.initialMessages ?? []);
  const [isConnecting, setIsConnecting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [charts, setCharts] = useState<ChartConfig[]>(options.initialCharts ?? []);
  const [focusedChartId, setFocusedChartId] = useState<string | null>(null);
  const [drilldowns, setDrilldowns] = useState<string[]>([]);
  const [activeDashboard, setActiveDashboard] = useState<DashboardData | null>(options.initialDashboard ?? null);
  const [documentQuery, setDocumentQuery] = useState<DocumentQueryResponse | null>(null);
  const [scenes, setScenes] = useState<VisualScene[]>([]);
  const onSaveRef = useRef(options.onSave);

  const pcRef = useRef<RTCPeerConnection | null>(null);
  const dcRef = useRef<RTCDataChannel | null>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const audioElRef = useRef<HTMLAudioElement | null>(null);
  const connectingRef = useRef(false);
  const greetingPendingRef = useRef(false);

  const currentAssistantIdRef = useRef<string | null>(null);
  const currentUserItemIdRef = useRef<string | null>(null);
  const pendingCallRef = useRef<PendingFunctionCall | null>(null);
  const filesRef = useRef(files);
  filesRef.current = files;
  const modeRef = useRef(mode);
  modeRef.current = mode;
  const langRef = useRef(language);
  langRef.current = language;

  // ── Response lifecycle tracking ────────────────────────
  // Prevents "conversation_already_has_active_response" errors
  const responseActiveRef = useRef(false);
  const pendingResponseCreateRef = useRef(false);

  // ── Send event on data channel ─────────────────────────
  const sendDC = useCallback((payload: Record<string, unknown>) => {
    const dc = dcRef.current;
    if (dc && dc.readyState === "open") {
      dc.send(JSON.stringify(payload));
      return true;
    }
    return false;
  }, []);

  /** Safe response.create — only sends if no response is currently active.
   *  If one is active, defers until response.done fires. */
  const requestResponse = useCallback(() => {
    if (responseActiveRef.current) {
      log("response", "Deferring response.create — response already active");
      pendingResponseCreateRef.current = true;
      return;
    }
    if (sendDC({ type: "response.create" })) {
      log("response", "Sent response.create");
    }
  }, [sendDC]);

  // ── Execute a tool call and send result back ───────────
  const executeTool = useCallback(
    async (call: PendingFunctionCall) => {
      log("tool", `┌ Executing: ${call.name} (call_id: ${call.callId})`);
      log("tool", `│ Raw args: ${call.args || "(empty)"}`);

      const args = safeParseArgs(call.args, call.name);
      log("tool", `│ Parsed args:`, args);

      // Try client-side first
      const clientResult = executeClientTool(call.name, args, filesRef.current);

      let resultText = "Tool execution produced no result.";
      let chartData: ChartConfig | null = null;

      if (clientResult) {
        resultText = clientResult.result;
        log("tool", `│ Resolved client-side`);
      } else {
        // Resolve file — with fallback to active/latest file
        const file = resolveFile(args, filesRef.current);
        const fileName = file?.name;

        log("tool", `│ File context: ${fileName ?? "none"} (${filesRef.current.length} files available)`);

        if (!file && call.name !== "list_uploaded_files") {
          const available = filesRef.current
            .filter((f) => f.status === "ready")
            .map((f) => f.name);
          if (available.length === 0) {
            resultText = "No files have been uploaded yet. Ask the user to upload a CSV, Excel, or PDF file.";
          } else if (args.file_name) {
            resultText = `Could not resolve file "${args.file_name}". Available files: ${available.join(", ")}. Specify the exact file name.`;
          } else {
            resultText = `Multiple files are uploaded: ${available.join(", ")}. Specify which file to use by setting file_name.`;
          }
          log("tool", `│ No file resolved`);
        } else if (call.name !== "list_uploaded_files") {
          // Phase 9 — these need to live in the outer scope so the `finally`
          // block below can clean up the polling timer + skeleton even when
          // the request throws. let-declarations inside `try` aren't visible
          // in `catch`/`finally` in JS, so we hoist.
          const isLongTool = LONG_RUNNING_TOOLS.has(call.name);
          const traceId = isLongTool
            ? (typeof crypto !== "undefined" && "randomUUID" in crypto
                ? crypto.randomUUID()
                : `trace_${Date.now()}_${Math.random().toString(36).slice(2)}`)
            : null;
          const skeletonId = traceId ? `scene_skeleton_${traceId}` : null;
          let pollHandle: ReturnType<typeof setInterval> | null = null;

          try {
            // Override file_name in args with the resolved name
            const resolvedArgs = fileName
              ? { ...args, file_name: fileName }
              : args;

            // For compare_files, resolve second file
            let parsedDataB: unknown = undefined;
            if (call.name === "compare_files" && args.file_name_b) {
              const fileB = filesRef.current.find(
                (f) => f.name.toLowerCase() === String(args.file_name_b).toLowerCase() && f.status === "ready"
              ) ?? filesRef.current.find(
                (f) => f.name.toLowerCase().includes(String(args.file_name_b).toLowerCase()) && f.status === "ready"
              );
              if (fileB) {
                parsedDataB = fileB.parsedData;
                log("tool", `│ Second file for comparison: ${fileB.name}`);
              }
            }

            const fetchTimeoutMs = isLongTool
              ? LLM_TOOL_FETCH_TIMEOUT_MS
              : TOOL_FETCH_TIMEOUT_MS;

            // Phase 9: for long tools, push a progress skeleton immediately
            // so the screen isn't blank while the tool runs. Open a polling
            // loop against /api/tools/progress/[traceId] and stream incoming
            // messages into the skeleton. The skeleton is replaced
            // atomically by the real scene below, or removed in `finally`
            // on error.
            if (isLongTool && skeletonId && traceId) {
              const startedAt = new Date().toISOString();
              const skeleton: VisualScene = {
                id: skeletonId,
                title: fileName ? `Working on ${fileName}…` : "Working on it…",
                layout: "stack",
                fragments: [
                  progressSkeletonFragment({
                    toolName: call.name,
                    fileName,
                    question: typeof args.question === "string" ? args.question : undefined,
                    messages: [],
                    startedAt,
                  }),
                ],
                createdAt: startedAt,
              };
              setScenes((prev) => [...prev, skeleton]);

              let cursor: string | null = null;
              pollHandle = setInterval(async () => {
                try {
                  const url = new URL(
                    `/api/tools/progress/${traceId}`,
                    window.location.origin
                  );
                  if (cursor) url.searchParams.set("since", cursor);
                  const r = await fetch(url.toString());
                  if (!r.ok) return;
                  const body = (await r.json()) as {
                    events: Array<{
                      id: string;
                      kind: "phase" | "info" | "warn";
                      message: string;
                      createdAt: string;
                    }>;
                  };
                  if (!body.events || body.events.length === 0) return;
                  cursor = body.events[body.events.length - 1].createdAt;
                  setScenes((prev) =>
                    prev.map((s) => {
                      if (s.id !== skeletonId) return s;
                      const frag = s.fragments[0];
                      if (frag.kind !== "progress_skeleton") return s;
                      const newMessages = [
                        ...frag.props.messages,
                        ...body.events.map((e) => ({
                          kind: e.kind,
                          text: e.message,
                          at: e.createdAt,
                        })),
                      ];
                      return {
                        ...s,
                        fragments: [
                          { ...frag, props: { ...frag.props, messages: newMessages } },
                        ],
                      };
                    })
                  );
                } catch {
                  // Polling errors are non-fatal — just try again next tick.
                }
              }, PROGRESS_POLL_INTERVAL_MS);
            }

            const res = await fetch("/api/tools/execute", {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                ...(traceId ? { "X-Trace-Id": traceId } : {}),
              },
              body: JSON.stringify({
                tool: call.name,
                args: resolvedArgs,
                fileContent: file?.content,
                fileName,
                parsedData: file?.parsedData,
                ...(parsedDataB ? { parsedDataB } : {}),
              }),
              signal: AbortSignal.timeout(fetchTimeoutMs),
            });

            if (!res.ok) {
              const errBody = (await res.json().catch(() => ({ error: "Unknown server error" }))) as { error: string };
              resultText = `Error: ${errBody.error}`;
              logError("tool", `│ Server error:`, errBody.error);
            } else {
              const data = (await res.json()) as BridgeToolResult;
              resultText = data.result;
              if (data.chart) chartData = data.chart;
              if (data.dashboard) {
                setActiveDashboard(data.dashboard);
                log("tool", `│ Dashboard generated: ${data.dashboard.title}`);
              }
              if (data.drilldowns && data.drilldowns.length > 0) {
                setDrilldowns(data.drilldowns);
              }
              if (data.documentResponse) {
                setDocumentQuery({
                  fileName: fileName ?? "(unknown)",
                  ...data.documentResponse,
                  timestamp: Date.now(),
                });
                // v1 (query_document) returns facts[]; v2 (query_document_v2)
                // returns passages[]. Both expose citations[]. Defensive
                // optional-chaining keeps the log line robust to either shape.
                const dr = data.documentResponse as {
                  confidence?: string;
                  facts?: unknown[];
                  passages?: unknown[];
                  citations?: unknown[];
                };
                log(
                  "tool",
                  `│ Document query result: confidence=${dr.confidence}, ` +
                    `facts=${dr.facts?.length ?? 0}, ` +
                    `passages=${dr.passages?.length ?? 0}, ` +
                    `citations=${dr.citations?.length ?? 0}`
                );
              }

              // ── Phase 3: bridge tool results into VisualScenes ──
              // The bridge converts each kind of tool result into a scene
              // and appends it to the unified scenes array. SceneStage
              // renders from here regardless of which tool produced the data.
              const bridged = bridgeToolResultToScene(call.name, data, file, args);
              if (bridged) {
                // Atomic swap: if a skeleton was shown for this tool call,
                // remove it in the same setScenes update that adds the real
                // scene. Avoids a one-frame flicker where both are visible.
                setScenes((prev) => {
                  const withoutSkeleton = skeletonId
                    ? prev.filter((s) => s.id !== skeletonId)
                    : prev;
                  return [...withoutSkeleton, bridged];
                });
                log("scenes", `│ Composed scene: ${bridged.title} (${bridged.layout}, ${bridged.fragments.length} fragments)`);
              }

              log("tool", `│ Server OK`);
            }
          } catch (err) {
            if (err instanceof DOMException && err.name === "TimeoutError") {
              const usedTimeoutMs = LONG_RUNNING_TOOLS.has(call.name)
                ? LLM_TOOL_FETCH_TIMEOUT_MS
                : TOOL_FETCH_TIMEOUT_MS;
              resultText = `Tool timed out after ${usedTimeoutMs / 1000}s. The document may be too long; ask a more specific question or retry — extraction results are cached after the first successful query.`;
            } else {
              resultText = `Tool execution failed: ${err instanceof Error ? err.message : "unknown error"}`;
            }
            logError("tool", `│ Exception:`, resultText);
          } finally {
            // Phase 9: stop polling and remove the skeleton. If the success
            // path already swapped it for the real scene, the filter is a
            // no-op. On error, this is what cleans up the skeleton so the
            // user doesn't stare at a stuck loading state.
            if (pollHandle) clearInterval(pollHandle);
            if (skeletonId) {
              setScenes((prev) => prev.filter((s) => s.id !== skeletonId));
            }
          }
        }
      }

      // Show chart if generated
      if (chartData) {
        const chartWithId = { ...chartData, id: `chart-${Date.now()}` };
        setCharts((prev) => [...prev, chartWithId]);
        setFocusedChartId(chartWithId.id);
        log("tool", `│ Chart created: ${chartData.title}`);
      }

      log("tool", `└ Done: ${call.name}`);

      // Send result back to the assistant
      sendDC({
        type: "conversation.item.create",
        item: {
          type: "function_call_output",
          call_id: call.callId,
          output: resultText,
        },
      });

      // Trigger the assistant to continue — using the safe guard
      requestResponse();
    },
    [sendDC, requestResponse]
  );

  // ── Cleanup ────────────────────────────────────────────
  const cleanup = useCallback(() => {
    log("lifecycle", "Cleaning up session resources");

    if (dcRef.current) {
      dcRef.current.onopen = null;
      dcRef.current.onmessage = null;
      dcRef.current.onclose = null;
      dcRef.current.close();
      dcRef.current = null;
    }

    if (pcRef.current) {
      pcRef.current.ontrack = null;
      pcRef.current.oniceconnectionstatechange = null;
      pcRef.current.close();
      pcRef.current = null;
    }

    streamRef.current?.getTracks().forEach((t) => t.stop());
    streamRef.current = null;

    if (audioElRef.current) {
      audioElRef.current.pause();
      audioElRef.current.srcObject = null;
      audioElRef.current = null;
    }

    currentAssistantIdRef.current = null;
    currentUserItemIdRef.current = null;
    pendingCallRef.current = null;
    connectingRef.current = false;
    greetingPendingRef.current = false;
    responseActiveRef.current = false;
    pendingResponseCreateRef.current = false;
  }, []);

  // Keep onSave ref current
  onSaveRef.current = options.onSave;

  const disconnect = useCallback(() => {
    // Persist state before tearing down
    if (onSaveRef.current) {
      // Read latest state via setState callbacks to avoid stale closures
      setMessages((msgs) => {
        setCharts((chts) => {
          setActiveDashboard((dash) => {
            if (msgs.length > 0 || chts.length > 0 || dash) {
              onSaveRef.current?.({ messages: msgs, charts: chts, dashboard: dash, outputMode: mode });
            }
            return dash;
          });
          return chts;
        });
        return msgs;
      });
    }

    cleanup();
    setSessionStatus("disconnected");
    setOrbState("idle");
    setIsConnecting(false);
    setError(null);
    log("lifecycle", "Disconnected (state saved)");
  }, [cleanup, mode]);

  // ── Handle data-channel events ─────────────────────────
  const handleServerEvent = useCallback(
    (evt: RealtimeServerEvent) => {
      switch (evt.type) {
        case "session.created":
          setSessionStatus("connected");
          setOrbState("idle");
          log("session", "session.created");
          if (dcRef.current?.readyState === "open") {
            requestResponse();
          } else {
            greetingPendingRef.current = true;
          }
          break;

        case "session.updated":
          setSessionStatus("connected");
          setOrbState("idle");
          break;

        case "input_audio_buffer.speech_started":
          setOrbState("listening");
          {
            const id = `user-${Date.now()}`;
            currentUserItemIdRef.current = id;
            setMessages((prev) => [
              ...prev,
              { id, role: "user", content: "", timestamp: Date.now(), streaming: true },
            ]);
          }
          break;

        case "input_audio_buffer.speech_stopped":
          setOrbState("thinking");
          if (currentUserItemIdRef.current) {
            const uid = currentUserItemIdRef.current;
            setMessages((prev) =>
              prev.map((m) => (m.id === uid ? { ...m, streaming: false } : m))
            );
          }
          break;

        case "conversation.item.input_audio_transcription.delta": {
          const delta = evt.delta as string | undefined;
          const itemId = currentUserItemIdRef.current;
          if (itemId && delta) {
            setMessages((prev) =>
              prev.map((m) =>
                m.id === itemId ? { ...m, content: m.content + delta } : m
              )
            );
          }
          break;
        }

        case "conversation.item.input_audio_transcription.completed": {
          const transcript = evt.transcript as string | undefined;
          const itemId = currentUserItemIdRef.current;
          if (itemId && transcript) {
            setMessages((prev) =>
              prev.map((m) =>
                m.id === itemId ? { ...m, content: transcript, streaming: false } : m
              )
            );
          }
          currentUserItemIdRef.current = null;
          break;
        }

        // ── Response lifecycle ───────────────────────────
        case "response.created": {
          responseActiveRef.current = true;
          setOrbState("thinking");
          const response = evt.response as { id: string } | undefined;
          currentAssistantIdRef.current = response?.id ?? `resp-${Date.now()}`;
          log("response", `Active: ${currentAssistantIdRef.current}`);
          break;
        }

        case "response.done": {
          responseActiveRef.current = false;
          currentAssistantIdRef.current = null;
          log("response", "Done");

          // Flush any deferred response.create
          if (pendingResponseCreateRef.current) {
            pendingResponseCreateRef.current = false;
            log("response", "Flushing deferred response.create");
            // Small delay to let the server process the done event
            setTimeout(() => requestResponse(), 50);
          }
          break;
        }

        case "response.output_item.added": {
          const item = evt.item as { type?: string; call_id?: string; name?: string; id?: string } | undefined;
          if (item?.type === "function_call") {
            pendingCallRef.current = {
              callId: item.call_id ?? item.id ?? `call-${Date.now()}`,
              name: item.name ?? "unknown",
              args: "",
            };
            log("tool", `Function call started: ${item.name}`);
          } else if (item?.type === "message") {
            const rid = currentAssistantIdRef.current;
            if (rid) {
              setMessages((prev) => {
                if (prev.some((m) => m.id === rid)) return prev;
                return [...prev, { id: rid, role: "assistant", content: "", timestamp: Date.now(), streaming: true }];
              });
            }
          }
          break;
        }

        case "response.function_call_arguments.delta": {
          const delta = evt.delta as string | undefined;
          if (pendingCallRef.current && delta) {
            pendingCallRef.current.args += delta;
          }
          break;
        }

        case "response.function_call_arguments.done": {
          const finalArgs = evt.arguments as string | undefined;
          if (pendingCallRef.current) {
            if (finalArgs) pendingCallRef.current.args = finalArgs;
            const call = { ...pendingCallRef.current };
            pendingCallRef.current = null;
            executeTool(call);
          }
          break;
        }

        case "response.audio_transcript.delta": {
          setOrbState("speaking");
          const delta = evt.delta as string | undefined;
          const rid = currentAssistantIdRef.current;
          if (rid && delta) {
            setMessages((prev) => {
              const exists = prev.some((m) => m.id === rid);
              if (!exists) {
                return [...prev, { id: rid, role: "assistant", content: delta, timestamp: Date.now(), streaming: true }];
              }
              return prev.map((m) => (m.id === rid ? { ...m, content: m.content + delta } : m));
            });
          }
          break;
        }

        case "response.audio_transcript.done": {
          const transcript = evt.transcript as string | undefined;
          const rid = currentAssistantIdRef.current;
          if (rid && transcript) {
            setMessages((prev) =>
              prev.map((m) => (m.id === rid ? { ...m, content: transcript, streaming: false } : m))
            );
          }
          break;
        }

        case "response.audio.done":
          setTimeout(() => setOrbState("idle"), 400);
          break;

        case "error": {
          const errObj = evt.error as { message?: string; code?: string } | undefined;
          const errMsg = errObj?.message ?? "Unknown error";
          const errCode = errObj?.code ?? "?";
          logError("event", `Server error (${errCode}): ${errMsg}`);
          // If error is about active response, clear the flag so deferred creates can proceed
          if (errCode === "conversation_already_has_active_response") {
            log("response", "Clearing active flag due to conflict error");
            // Don't show this to the user — it's an internal timing issue
            responseActiveRef.current = false;
          } else {
            setError(errMsg);
          }
          setOrbState("idle");
          break;
        }

        default:
          break;
      }
    },
    [executeTool, requestResponse]
  );

  // ── Connect ────────────────────────────────────────────
  const connect = useCallback(async () => {
    if (connectingRef.current) {
      log("lifecycle", "Connect already in progress, ignoring");
      return;
    }

    if (pcRef.current) {
      disconnect();
    }

    connectingRef.current = true;
    setIsConnecting(true);
    setError(null);
    setSessionStatus("connecting");
    setMessages([]);
    setCharts([]);
    setFocusedChartId(null);
    setScenes([]);

    try {
      log("lifecycle", "Requesting ephemeral token");
      const tokenRes = await fetch(`/api/realtime/session?mode=${modeRef.current}&lang=${langRef.current}`, {
        method: "POST",
        signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      });
      if (!tokenRes.ok) {
        const body = await tokenRes.json().catch(() => ({})) as { error?: string };
        throw new Error(body.error ?? `Session creation failed (${tokenRes.status})`);
      }
      const { clientSecret } = (await tokenRes.json()) as {
        clientSecret: string;
        expiresAt: number;
      };
      log("lifecycle", "Token received");

      log("lifecycle", "Requesting microphone access");
      let stream: MediaStream;
      try {
        stream = await navigator.mediaDevices.getUserMedia({
          audio: { echoCancellation: true, noiseSuppression: true, sampleRate: 24000 },
        });
      } catch (micErr) {
        throw new Error(classifyMicError(micErr));
      }
      streamRef.current = stream;
      log("lifecycle", "Microphone access granted");

      const pc = new RTCPeerConnection();
      pcRef.current = pc;

      pc.ontrack = (e) => {
        if (!audioElRef.current) {
          audioElRef.current = new Audio();
          audioElRef.current.autoplay = true;
        }
        audioElRef.current.srcObject = e.streams[0];
      };

      stream.getTracks().forEach((track) => pc.addTrack(track, stream));

      const dc = pc.createDataChannel("oai-events");
      dcRef.current = dc;

      dc.onopen = () => {
        setSessionStatus("connected");
        setIsConnecting(false);
        connectingRef.current = false;
        log("lifecycle", "Data channel open — session live");
        if (greetingPendingRef.current) {
          greetingPendingRef.current = false;
          requestResponse();
        }
      };

      dc.onmessage = (e) => {
        try {
          const event = JSON.parse(e.data) as RealtimeServerEvent;
          handleServerEvent(event);
        } catch (parseErr) {
          logError("dc", "Failed to parse data channel message:", parseErr);
        }
      };

      dc.onclose = () => {
        log("lifecycle", "Data channel closed");
        setSessionStatus("disconnected");
        setOrbState("idle");
      };

      pc.oniceconnectionstatechange = () => {
        const state = pc.iceConnectionState;
        log("ice", state);
        if (state === "failed" || state === "disconnected") {
          setSessionStatus("disconnected");
          setOrbState("idle");
          setError("Connection lost — tap the orb to reconnect");
          setIsConnecting(false);
          connectingRef.current = false;
        }
      };

      log("lifecycle", "Starting SDP negotiation");
      const offer = await pc.createOffer();
      await pc.setLocalDescription(offer);

      const sdpRes = await fetch(
        `${OPENAI_REALTIME_URL}?model=${MODEL}`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${clientSecret}`,
            "Content-Type": "application/sdp",
          },
          body: offer.sdp,
          signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
        }
      );

      if (!sdpRes.ok) {
        const errorBody = await sdpRes.text();
        logError("sdp", `Negotiation failed (${sdpRes.status}):`, errorBody);
        throw new Error(`WebRTC negotiation failed (${sdpRes.status})`);
      }

      const answerSdp = await sdpRes.text();
      await pc.setRemoteDescription({ type: "answer", sdp: answerSdp });
      log("lifecycle", "SDP negotiation complete — WebRTC connected");
    } catch (err) {
      let msg: string;
      if (err instanceof DOMException && err.name === "TimeoutError") {
        msg = "Connection timed out. Please check your network and try again.";
      } else {
        msg = err instanceof Error ? err.message : "Connection failed";
      }
      logError("connect", msg);
      setError(msg);
      setSessionStatus("error");
      setOrbState("idle");
      setIsConnecting(false);
      connectingRef.current = false;
      cleanup();
    }
  }, [disconnect, cleanup, handleServerEvent, requestResponse]);

  // ── Send file context ──────────────────────────────────
  const sendFileContext = useCallback(
    (
      fileName: string,
      _content: string,
      parsedData?: ParsedData,
      extraction?: import("@/lib/documents/types").DocumentExtraction,
      hasPassages: boolean = false
    ) => {
      // SAFETY: Send ONLY metadata to the AI — never raw file content or
      // narrative document text. The AI must use tools to access data.
      // Keep common filename characters intact so the agent uses a name
      // that matches what we persisted. Parens, brackets, ampersands, commas
      // are all safe inside double-quoted metadata. Strip only characters
      // that could plausibly disrupt the surrounding prompt structure
      // (quotes, angle brackets, backticks, newlines).
      const safeName = fileName.replace(/["`<>\r\n]/g, "");

      // Phase 2: classify the file as tabular or narrative so the model
      // picks the right tool. Tabular = has rows; narrative = has pageCount
      // and either type is contract/report/memo/policy/financial_statement/etc.
      const NARRATIVE_TYPES = new Set([
        "contract",
        "policy",
        "report",
        "memo",
        "financial_statement",
        "invoice",
        "receipt",
        "form",
      ]);
      const isTabular =
        (parsedData?.totalRows ?? 0) > 0 ||
        (extraction?.tables && extraction.tables.length > 0);
      const isNarrative =
        !isTabular && extraction && NARRATIVE_TYPES.has(extraction.type);

      let metadata: string;

      if (isNarrative && extraction) {
        const subtype = extraction.subtype ? ` (${extraction.subtype})` : "";
        const pages = extraction.pageCount ? `\nPages: ${extraction.pageCount}` : "";
        const ragLine = hasPassages
          ? `has_passages: true — USE query_document_v2 (RAG, fast, accurate).`
          : `has_passages: false — USE query_document (legacy fallback).`;
        metadata =
          `File uploaded: "${safeName}"\n` +
          `Document type: ${extraction.type}${subtype}${pages}\n` +
          `${ragLine}\n\n` +
          `This is a NARRATIVE document. Ask grounded questions via the tool indicated above. ` +
          `Do NOT call profile_dataset / run_analysis / create_chart on this file — they only work on spreadsheets. ` +
          `When in doubt about a question, pick focus="general".`;
      } else if (parsedData && parsedData.columns.length > 0) {
        const pd = parsedData;
        const colList = pd.columns
          .map((c: string) => `${c} (${pd.columnTypes[c] ?? "unknown"})`)
          .join(", ");
        metadata =
          `File uploaded: "${safeName}"\n` +
          `Document type: spreadsheet\n` +
          `Rows: ${parsedData.totalRows}\n` +
          `Columns: ${colList}\n\n` +
          `Use profile_dataset to explore. Do NOT guess column names — use the exact names listed above. ` +
          `Do NOT call query_document on this file — it's tabular, not narrative.`;
      } else {
        metadata =
          `File uploaded: "${safeName}"\n\n` +
          `Use list_uploaded_files to see what's available, then pick the right tool by document type.`;
      }

      if (!sendDC({
        type: "conversation.item.create",
        item: {
          type: "message",
          role: "user",
          content: [{ type: "input_text", text: metadata }],
        },
      })) {
        log("file", "Data channel not open — file context not sent");
        return;
      }

      setMessages((prev) => [
        ...prev,
        { id: `file-${Date.now()}`, role: "user", content: `Uploaded ${fileName}`, timestamp: Date.now() },
      ]);

      requestResponse();
      log("file", `Injected metadata for ${fileName} (no raw content sent, narrative=${!!isNarrative})`);
    },
    [sendDC, requestResponse]
  );

  const removeChart = useCallback((id: string) => {
    setCharts((prev) => prev.filter((c) => c.id !== id));
    setFocusedChartId((prev) => (prev === id ? null : prev));
  }, []);

  const clearCharts = useCallback(() => {
    setCharts([]);
    setFocusedChartId(null);
  }, []);

  const focusChart = useCallback((id: string) => {
    setFocusedChartId(id);
  }, []);

  /** Send a drill-down as a contextual follow-up — framed as continuation, not a new question */
  const sendDrilldown = useCallback(
    (text: string) => {
      // Frame as a continuation so the assistant doesn't restart from scratch
      const contextualPrompt = `Following up on what you just showed me: ${text}. Continue from where you left off — this is a drill-down, not a new question.`;

      if (!sendDC({
        type: "conversation.item.create",
        item: {
          type: "message",
          role: "user",
          content: [{ type: "input_text", text: contextualPrompt }],
        },
      })) {
        return;
      }

      // Show the short label in the transcript, not the full framing
      setMessages((prev) => [
        ...prev,
        { id: `drill-${Date.now()}`, role: "user", content: text, timestamp: Date.now() },
      ]);

      setDrilldowns([]);
      requestResponse();
      log("drilldown", `Sent: ${text}`);
    },
    [sendDC, requestResponse]
  );

  const closeDashboard = useCallback(() => setActiveDashboard(null), []);
  const removeScene = useCallback((id: string) => {
    setScenes((prev) => prev.filter((s) => s.id !== id));
  }, []);
  const clearScenes = useCallback(() => setScenes([]), []);
  void documentQuery; // referenced via return below — silences unused warnings

  useEffect(() => {
    return () => cleanup();
  }, [cleanup]);

  return {
    orbState,
    sessionStatus,
    messages,
    connect,
    disconnect,
    sendFileContext,
    isConnecting,
    error,
    charts,
    focusedChartId,
    removeChart,
    clearCharts,
    focusChart,
    drilldowns,
    sendDrilldown,
    activeDashboard,
    closeDashboard,
    documentQuery,
    scenes,
    removeScene,
    clearScenes,
  };
}
